name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
      - cron: "0 13 * * 1"  # Every Monday at 9AM EST

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: Test pre-commit hooks
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pre-commit run -a

  validate-types-and-docstrings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: Setup environment
        run: |
            python -m pip install --upgrade pip
            pip install ".[tests,dev]"

      - name: mypy type validation
        run: |
          mypy src
          mypy scripts

      - name: darglint docstring validation
        run: |
          darglint src --strictness=short --ignore-raise=ValueError
          darglint scripts --strictness=short --ignore-raise=ValueError

  diffractive_splitter_leaderboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: Setup environment
        run: |
            python -m pip install --upgrade pip
            pip install ".[tests,dev]"

      - name: Run Python tests
        run: |
          pytest tests/test_new_solutions.py::VerifyLeaderboardTest::test_all_solutions_on_leaderboard
          pytest tests/test_new_solutions.py::VerifyLeaderboardTest::test_diffractive_splitter

  ceviche_beam_splitter_leaderboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: Setup environment
        run: |
            python -m pip install --upgrade pip
            pip install ".[tests,dev]"

      - name: Run Python tests
        run: |
          pytest tests/test_new_solutions.py::VerifyLeaderboardTest::test_all_solutions_on_leaderboard
          pytest tests/test_new_solutions.py::VerifyLeaderboardTest::test_ceviche_beam_splitter

  ceviche_mode_converter_leaderboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: Setup environment
        run: |
            python -m pip install --upgrade pip
            pip install ".[tests,dev]"

      - name: Run Python tests
        run: |
          pytest tests/test_new_solutions.py::VerifyLeaderboardTest::test_all_solutions_on_leaderboard
          pytest tests/test_new_solutions.py::VerifyLeaderboardTest::test_ceviche_mode_converter

  ceviche_waveguide_bend_leaderboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: Setup environment
        run: |
            python -m pip install --upgrade pip
            pip install ".[tests,dev]"

      - name: Run Python tests
        run: |
          pytest tests/test_new_solutions.py::VerifyLeaderboardTest::test_all_solutions_on_leaderboard
          pytest tests/test_new_solutions.py::VerifyLeaderboardTest::test_ceviche_waveguide_bend

  ceviche_wdm_leaderboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: Setup environment
        run: |
            python -m pip install --upgrade pip
            pip install ".[tests,dev]"

      - name: Run Python tests
        run: |
          pytest tests/test_new_solutions.py::VerifyLeaderboardTest::test_all_solutions_on_leaderboard
          pytest tests/test_new_solutions.py::VerifyLeaderboardTest::test_ceviche_wdm

  meta_atom_library_leaderboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: Setup environment
        run: |
            python -m pip install --upgrade pip
            pip install ".[tests,dev]"

      - name: Run Python tests
        run: |
          pytest tests/test_new_solutions.py::VerifyLeaderboardTest::test_all_solutions_on_leaderboard
          pytest tests/test_new_solutions.py::VerifyLeaderboardTest::test_meta_atom_library

  metagrating_leaderboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: Setup environment
        run: |
            python -m pip install --upgrade pip
            pip install ".[tests,dev]"

      - name: Run Python tests
        run: |
          pytest tests/test_new_solutions.py::VerifyLeaderboardTest::test_all_solutions_on_leaderboard
          pytest tests/test_new_solutions.py::VerifyLeaderboardTest::test_metagrating

  metalens_leaderboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: Setup environment
        run: |
            python -m pip install --upgrade pip
            pip install ".[tests,dev]"

      - name: Run Python tests
        run: |
          pytest tests/test_new_solutions.py::VerifyLeaderboardTest::test_all_solutions_on_leaderboard
          pytest tests/test_new_solutions.py::VerifyLeaderboardTest::test_metalens

  photon_extractor_leaderboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: Setup environment
        run: |
            python -m pip install --upgrade pip
            pip install ".[tests,dev]"

      - name: Run Python tests
        run: |
          pytest tests/test_new_solutions.py::VerifyLeaderboardTest::test_all_solutions_on_leaderboard
          pytest tests/test_new_solutions.py::VerifyLeaderboardTest::test_photon_extractor
